### ISSUE TITLE
Country Restriction Change

### ISSUE THREAD

**Issue by kdaoudieh** [STS-Rosario/carpoolear#45]
- How can I change the restricted country?

**Comment by kdaoudieh** [comment]
** Update: I have managed to change the restricted country but I couldn't seem to view some town, also how can I add for it to search for places name example a university ** 

thanks

**Comment by p4bl1t0** [comment]
Maybe country restriction could be moved to and .env file.

Regarding to the visibility of somes town you should check the  [OsmAutocomplete.vue](https://github.com/STS-Rosario/carpoolear/blob/master/src/components/OsmAutocomplete.vue) file in order to see that what is coming from nominatin API. With that information you can check if it's an OSM issue or an issue in the filter function.

I dind't know if OSM nominatin allow to search places. Maybe you can consider using Google Maps at your own cost.

**Comment by kdaoudieh** [comment]
Hello, thanks very much for the reply I have solved the problem yesterday, I changed the osmautocomplete.vue and the osm.js a little bit so it can take the places, universities etc...  in the restricted country but still working on making it a little bit more efficient

also, I have merged the docker-compose file to run both backend and front end ^_^ , I'll be working on lots of things the coming days please let me know if there is anything I contribute to or help with thanks again.

**Comment by p4bl1t0** [comment]
Please share your fork, a make a Pull-Request with your changes.

With have a Trello with work to do. I you want to help please contact me at pabloluisbotta@gmail.com

**Comment by kdaoudieh** [comment]
Will be doing that very soon, I will send you an email with the details cause in my case I merged the front and backend into one repo so I can run them at once and the performance on the local machine when I did that increased in a noticeable way, I'm currently working on implementing the. application fo r my university at the moment will open a pull request when I'm done and when I organize my code and document it as well, also I might be contacting you just to get some information about the deployment and development environments so I can make more two docker-compose files for deployment and development, further more thanks for the reply, will be in contact soon.

**Comment by p4bl1t0** [comment]
Great news Khaled! Looking forward to hearing from you. And I you have any question please contact us.
